@startuml FX Comp Architecture
    interface FXCView           as "de.ruu.lib.fx.comp.FXCView"
    {
        getLocalRoot : javafx.scene.Parent
        getService   : FXCViewService
    }
    interface FXCViewController as "de.ruu.lib.fx.comp.FXCViewController"
    interface FXCViewService    as "de.ruu.lib.fx.comp.FXCViewService"
    abstract class FXCViewDefault
@enduml