package de.ruu.lib.fx.comp.demo.hierarchy.sub2;

import de.ruu.lib.fx.comp.FXCViewController;
import javafx.fxml.FXML;

/**
 * Java FX Component View Controller
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCViewController} at 2024.05.17 12:57:18:222
 */
public class HierarchyDemoSub2Controller extends FXCViewController.DefaultFXCViewController
{
	@Override @FXML
	protected void initialize()
	{
	}
}