package de.ruu.lib.fx.comp.demo.hierarchy.sub1;

import de.ruu.lib.fx.comp.DefaultFXCViewController;
import javafx.fxml.FXML;

/**
 * Java FX Component View Controller
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCViewController} at 2024.05.17 12:57:18:214
 */
public class HierarchyDemoSub1Controller extends DefaultFXCViewController
{
	@Override @FXML
	protected void initialize()
	{
	}
}