package de.ruu.lib.fx.comp.demo.empty;

import de.ruu.lib.fx.comp.DefaultFXCViewController;
import javafx.fxml.FXML;

/**
 * Java FX Component View Controller
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCViewController} at 2024.05.25 17:20:51:878
 */
class EmptyController extends DefaultFXCViewController
{
	@Override @FXML
	protected void initialize()
	{
	}
}