package de.ruu.lib.fx.demo.comp.main;

import de.ruu.lib.fx.comp.DefaultFXCViewController;
import javafx.fxml.FXML;

/**
 * Java FX Component View Controller
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCViewController} at 2024.05.20 14:28:47:941
 */
public class RUUFXDemoComponentMainController extends DefaultFXCViewController
{
	@Override @FXML
	protected void initialize()
	{
	}
}