alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
alias cd-config-docker='cd ~/config/docker'
alias docker-daemon-start='sudo service docker start'
alias docker-daemon-stop=' sudo service docker stop'
alias docker-system-prune='sudo docker system prune --all --volumes --force && sudo docker volume prune --all --force'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias grep='grep --color=auto'
alias l='ls -CF'
alias la='ls -A'
alias ll='ls -alF'
alias ls='ls --color=auto'
alias postgres-start='     cd-config-docker   && docker-compose up -d postgres'
alias postgres-stop='docker container stop postgres'
alias shell-reset='clear && exec /bin/bash'
alias update-docker='chmod +x ~/config/wsl/bash/update-docker.sh && ~/config/wsl/bash/update-docker.sh'